Remove bun-sh specifics on workflow
- Raise timeouts by 3x as these are free basic runners, and no longer macos-12-large
- Remove stuff that notifies about the build
- Remove tests and related notifications

diff --git a/.github/workflows/bun-mac-x64-baseline.yml b/.github/workflows/bun-mac-x64-baseline.yml
--- a/.github/workflows/bun-mac-x64-baseline.yml
+++ b/.github/workflows/bun-mac-x64-baseline.yml
@@ -7,6 +7,7 @@ concurrency:
 env:
   LLVM_VERSION: 16
   BUN_DOWNLOAD_URL_BASE: https://pub-5e11e972747a44bf9aaf9394f185a982.r2.dev/releases/latest
+  MACOSX_DEPLOYMENT_TARGET: "10.13"
 
 on:
   push:
@@ -38,7 +39,7 @@ jobs:
   macos-object-files:
     name: macOS Object
     runs-on: namespace-profile-zig-build
-    if: github.repository_owner == 'oven-sh'
+    if: github.repository_owner == 'cristianl'
     strategy:
       matrix:
         include:
@@ -83,8 +84,8 @@ jobs:
   macOS-dependencies:
     name: macOS Dependencies
     runs-on: ${{ matrix.runner }}
-    if: github.repository_owner == 'oven-sh'
-    timeout-minutes: 15
+    if: github.repository_owner == 'cristianl'
+    timeout-minutes: 45
     strategy:
       matrix:
         include:
@@ -92,7 +93,7 @@ jobs:
             arch: x86_64
             tag: bun-darwin-x64-baseline
             obj: bun-obj-darwin-x64-baseline
-            runner: macos-12-large
+            runner: macos-12
             artifact: bun-obj-darwin-x64-baseline
     steps:
       - uses: actions/checkout@v4
@@ -158,8 +159,8 @@ jobs:
   macOS-cpp:
     name: macOS C++
     runs-on: ${{ matrix.runner }}
-    if: github.repository_owner == 'oven-sh'
-    timeout-minutes: 90
+    if: github.repository_owner == 'cristianl'
+    timeout-minutes: 270
     strategy:
       matrix:
         include:
@@ -167,7 +168,7 @@ jobs:
             arch: x86_64
             tag: bun-darwin-x64-baseline
             obj: bun-obj-darwin-x64-baseline
-            runner: macos-12-large
+            runner: macos-12
             artifact: bun-obj-darwin-x64-baseline
     steps:
       - uses: actions/checkout@v4
@@ -229,9 +230,9 @@ jobs:
   macOS:
     name: macOS Link
     runs-on: ${{ matrix.runner }}
-    if: github.repository_owner == 'oven-sh'
+    if: github.repository_owner == 'cristianl'
     needs: [macOS-cpp, macos-object-files, macOS-dependencies]
-    timeout-minutes: 90
+    timeout-minutes: 270
     permissions: write-all
     strategy:
       matrix:
@@ -241,7 +242,7 @@ jobs:
             tag: bun-darwin-x64-baseline
             obj: bun-obj-darwin-x64-baseline
             package: bun-darwin-x64
-            runner: macos-12-large
+            runner: macos-12
             artifact: bun-obj-darwin-x64-baseline
     steps:
       - uses: actions/checkout@v4
@@ -324,146 +325,146 @@ jobs:
           name: ${{matrix.tag}}
           path: ${{runner.temp}}/link-build/${{matrix.tag}}.zip
           if-no-files-found: "error"
-      - name: Release
-        id: release
-        uses: ncipollo/release-action@v1
-        if: |
-          github.repository_owner == 'oven-sh'
-          && github.ref == 'refs/heads/main'
-        with:
-          prerelease: true
-          body: "This canary release of Bun corresponds to the commit [${{ github.sha }}]"
-          allowUpdates: true
-          replacesArtifacts: true
-          generateReleaseNotes: true
-          artifactErrorsFailBuild: true
-          token: ${{ secrets.GITHUB_TOKEN }}
-          name: "Canary (${{github.sha}})"
-          tag: "canary"
-          artifacts: "${{runner.temp}}/link-build/${{matrix.tag}}.zip,${{runner.temp}}/link-build/${{matrix.tag}}-profile.zip"
-      - uses: sarisia/actions-status-discord@v1
-        if: failure() && github.repository_owner == 'oven-sh' && github.event_name == 'pull_request'
-        with:
-          title: ""
-          webhook: ${{ secrets.DISCORD_WEBHOOK }}
-          status: ${{ job.status }}
-          noprefix: true
-          nocontext: true
-          description: |
-            Pull Request
-            ### [${{github.event.pull_request.title}}](https://github.com/oven-sh/bun/pull/${{github.event.number}})
+      # - name: Release
+      #   id: release
+      #   uses: ncipollo/release-action@v1
+      #   if: |
+      #     github.repository_owner == 'cristianl'
+      #     && github.ref == 'refs/heads/main'
+      #   with:
+      #     prerelease: true
+      #     body: "This canary release of Bun corresponds to the commit [${{ github.sha }}]"
+      #     allowUpdates: true
+      #     replacesArtifacts: true
+      #     generateReleaseNotes: true
+      #     artifactErrorsFailBuild: true
+      #     token: ${{ secrets.GITHUB_TOKEN }}
+      #     name: "Canary (${{github.sha}})"
+      #     tag: "canary"
+      #     artifacts: "${{runner.temp}}/link-build/${{matrix.tag}}.zip,${{runner.temp}}/link-build/${{matrix.tag}}-profile.zip"
+      # - uses: sarisia/actions-status-discord@v1
+      #   if: failure() && github.repository_owner == 'cristianl' && github.event_name == 'pull_request'
+      #   with:
+      #     title: ""
+      #     webhook: ${{ secrets.DISCORD_WEBHOOK }}
+      #     status: ${{ job.status }}
+      #     noprefix: true
+      #     nocontext: true
+      #     description: |
+      #       Pull Request
+      #       ### [${{github.event.pull_request.title}}](https://github.com/oven-sh/bun/pull/${{github.event.number}})
 
-            @${{ github.actor }}
+      #       @${{ github.actor }}
 
-            Build failed on ${{ matrix.tag }}:
+      #       Build failed on ${{ matrix.tag }}:
 
-            **[View build output](https://github.com/oven-sh/bun/actions/runs/${{github.run_id}})**
+      #       **[View build output](https://github.com/oven-sh/bun/actions/runs/${{github.run_id}})**
 
-            [Commit ${{github.sha}}](https://github.com/oven-sh/bun/commits/${{github.sha}})
-  macOS-test:
-    name: macOS Test
-    runs-on: ${{ matrix.runner }}
-    needs: [macOS]
-    # if: github.event_name == 'pull_request' && github.repository_owner == 'oven-sh'
-    if: false
-    permissions:
-      pull-requests: write
-    timeout-minutes: 30
-    outputs:
-      failing_tests: ${{ steps.test.outputs.failing_tests }}
-      failing_tests_count: ${{ steps.test.outputs.failing_tests_count }}
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - tag: bun-darwin-x64-baseline
-            runner: macos-12-large
-    steps:
-      - id: checkout
-        name: Checkout
-        uses: actions/checkout@v4
-        with:
-          submodules: false
-      - id: download
-        name: Download
-        uses: actions/download-artifact@v4
-        with:
-          name: ${{matrix.tag}}
-          path: ${{runner.temp}}/release
-      - id: install-bun
-        name: Install Bun
-        run: |
-          cd ${{runner.temp}}/release
-          unzip ${{matrix.tag}}.zip
-          cd ${{matrix.tag}}
-          chmod +x bun
-          pwd >> $GITHUB_PATH
-      - id: bun-version-check
-        name: Bun version check
-        run: |
-          # If this hangs, it means something is seriously wrong with the build
-          bun --version
-      - id: install
-        name: Install dependencies
-        run: |
-          bun install --verbose
-          bun install --cwd=test --verbose
-          bun install --cwd=packages/bun-internal-test --verbose
-      - id: test
-        name: Test (node runner)
-        env:
-          SMTP_SENDGRID_SENDER: ${{ secrets.SMTP_SENDGRID_SENDER }}
-          TMPDIR: ${{runner.temp}}
-          TLS_MONGODB_DATABASE_URL: ${{ secrets.TLS_MONGODB_DATABASE_URL }}
-          TLS_POSTGRES_DATABASE_URL: ${{ secrets.TLS_POSTGRES_DATABASE_URL }}
-        # if: ${{github.event.inputs.use_bun == 'false'}}
-        run: |
-          node packages/bun-internal-test/src/runner.node.mjs || true
-      - uses: sarisia/actions-status-discord@v1
-        if: always() && steps.test.outputs.failing_tests != '' && github.event_name == 'pull_request'
-        with:
-          title: ""
-          webhook: ${{ secrets.DISCORD_WEBHOOK }}
-          status: "failure"
-          noprefix: true
-          nocontext: true
-          description: |
-            Pull Request
-            ### ❌ [${{github.event.pull_request.title}}](https://github.com/oven-sh/bun/pull/${{github.event.number}})
+      #       [Commit ${{github.sha}}](https://github.com/oven-sh/bun/commits/${{github.sha}})
+  # macOS-test:
+  #   name: macOS Test
+  #   runs-on: ${{ matrix.runner }}
+  #   needs: [macOS]
+  #   # if: github.event_name == 'pull_request' && github.repository_owner == 'cristianl'
+  #   if: false
+  #   permissions:
+  #     pull-requests: write
+  #   timeout-minutes: 30
+  #   outputs:
+  #     failing_tests: ${{ steps.test.outputs.failing_tests }}
+  #     failing_tests_count: ${{ steps.test.outputs.failing_tests_count }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       include:
+  #         - tag: bun-darwin-x64-baseline
+  #           runner: macos-12
+  #   steps:
+  #     - id: checkout
+  #       name: Checkout
+  #       uses: actions/checkout@v4
+  #       with:
+  #         submodules: false
+  #     - id: download
+  #       name: Download
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: ${{matrix.tag}}
+  #         path: ${{runner.temp}}/release
+  #     - id: install-bun
+  #       name: Install Bun
+  #       run: |
+  #         cd ${{runner.temp}}/release
+  #         unzip ${{matrix.tag}}.zip
+  #         cd ${{matrix.tag}}
+  #         chmod +x bun
+  #         pwd >> $GITHUB_PATH
+  #     - id: bun-version-check
+  #       name: Bun version check
+  #       run: |
+  #         # If this hangs, it means something is seriously wrong with the build
+  #         bun --version
+  #     - id: install
+  #       name: Install dependencies
+  #       run: |
+  #         bun install --verbose
+  #         bun install --cwd=test --verbose
+  #         bun install --cwd=packages/bun-internal-test --verbose
+  #     - id: test
+  #       name: Test (node runner)
+  #       env:
+  #         SMTP_SENDGRID_SENDER: ${{ secrets.SMTP_SENDGRID_SENDER }}
+  #         TMPDIR: ${{runner.temp}}
+  #         TLS_MONGODB_DATABASE_URL: ${{ secrets.TLS_MONGODB_DATABASE_URL }}
+  #         TLS_POSTGRES_DATABASE_URL: ${{ secrets.TLS_POSTGRES_DATABASE_URL }}
+  #       # if: ${{github.event.inputs.use_bun == 'false'}}
+  #       run: |
+  #         node packages/bun-internal-test/src/runner.node.mjs || true
+  #     - uses: sarisia/actions-status-discord@v1
+  #       if: always() && steps.test.outputs.failing_tests != '' && github.event_name == 'pull_request'
+  #       with:
+  #         title: ""
+  #         webhook: ${{ secrets.DISCORD_WEBHOOK }}
+  #         status: "failure"
+  #         noprefix: true
+  #         nocontext: true
+  #         description: |
+  #           Pull Request
+  #           ### ❌ [${{github.event.pull_request.title}}](https://github.com/oven-sh/bun/pull/${{github.event.number}})
 
-            Hey @${{ github.actor }},
+  #           Hey @${{ github.actor }},
 
-            ${{ steps.test.outputs.failing_tests_count }} files with test failures on ${{ matrix.tag }}:
+  #           ${{ steps.test.outputs.failing_tests_count }} files with test failures on ${{ matrix.tag }}:
 
-            ${{ steps.test.outputs.failing_tests }}
+  #           ${{ steps.test.outputs.failing_tests }}
 
-            **[View test output](https://github.com/oven-sh/bun/actions/runs/${{github.run_id}})**
+  #           **[View test output](https://github.com/oven-sh/bun/actions/runs/${{github.run_id}})**
 
-      - name: Comment on PR
-        if: steps.test.outputs.failing_tests != '' && github.event_name == 'pull_request'
-        uses: thollander/actions-comment-pull-request@v2
-        with:
-          comment_tag: test-failures-${{matrix.tag}}
-          message: |
-            ❌ @${{ github.actor }} ${{ steps.test.outputs.failing_tests_count }} files with test failures on ${{ matrix.tag }}:
+  #     - name: Comment on PR
+  #       if: steps.test.outputs.failing_tests != '' && github.event_name == 'pull_request'
+  #       uses: thollander/actions-comment-pull-request@v2
+  #       with:
+  #         comment_tag: test-failures-${{matrix.tag}}
+  #         message: |
+  #           ❌ @${{ github.actor }} ${{ steps.test.outputs.failing_tests_count }} files with test failures on ${{ matrix.tag }}:
 
-            ${{ steps.test.outputs.failing_tests }}
+  #           ${{ steps.test.outputs.failing_tests }}
 
-            **[View test output](https://github.com/oven-sh/bun/actions/runs/${{github.run_id}})**
+  #           **[View test output](https://github.com/oven-sh/bun/actions/runs/${{github.run_id}})**
 
-            <sup>[#${{github.sha}}](https://github.com/oven-sh/bun/commits/${{github.sha}})</sup>
-      - name: Uncomment on PR
-        if: steps.test.outputs.failing_tests == '' && github.event_name == 'pull_request'
-        uses: thollander/actions-comment-pull-request@v2
-        with:
-          comment_tag: test-failures-${{matrix.tag}}
-          mode: upsert
-          create_if_not_exists: false
-          message: |
-            ✅ test failures on ${{ matrix.tag }} have been resolved.
+  #           <sup>[#${{github.sha}}](https://github.com/oven-sh/bun/commits/${{github.sha}})</sup>
+  #     - name: Uncomment on PR
+  #       if: steps.test.outputs.failing_tests == '' && github.event_name == 'pull_request'
+  #       uses: thollander/actions-comment-pull-request@v2
+  #       with:
+  #         comment_tag: test-failures-${{matrix.tag}}
+  #         mode: upsert
+  #         create_if_not_exists: false
+  #         message: |
+  #           ✅ test failures on ${{ matrix.tag }} have been resolved.
 
-            <sup>[#${{github.sha}}](https://github.com/oven-sh/bun/commits/${{github.sha}})</sup>
-      - id: fail
-        name: Fail the build
-        if: steps.test.outputs.failing_tests != ''
-        run: exit 1
+  #           <sup>[#${{github.sha}}](https://github.com/oven-sh/bun/commits/${{github.sha}})</sup>
+  #     - id: fail
+  #       name: Fail the build
+  #       if: steps.test.outputs.failing_tests != ''
+  #       run: exit 1
